/**
 * Transfusion API
 * API used for the transfusion centers: user administration, reservation management and transfusion auditing.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Sex } from './sex';

export interface CreateDonorCommand { 
    userName?: string;
    password?: string;
    firstName?: string;
    lastName?: string;
    sex?: Sex;
    jmbg?: string;
    state?: string;
    homeAddress?: string;
    city?: string;
    phoneNumber?: string;
    occupation?: string;
    occupationInfo?: string;
}