/**
 * Transfusion API
 * API used for the transfusion centers: user administration, reservation management and transfusion auditing.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from './sex.model';


export interface CreatedDonorDto { 
    readonly id?: number;
    readonly applicationUserId?: string | null;
    readonly firstName?: string | null;
    readonly lastName?: string | null;
    sex?: Sex;
    readonly jmbg?: string | null;
    readonly state?: string | null;
    readonly homeAddress?: string | null;
    readonly city?: string | null;
    readonly phoneNumber?: string | null;
    readonly occupation?: string | null;
    readonly occupationInfo?: string | null;
}

