/**
 * Transfusion API
 * API used for the transfusion centers: user administration, reservation management and transfusion auditing.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from './sex.model';


export interface CreateDonorCommand { 
    userName?: string | null;
    password?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    sex?: Sex;
    jmbg?: string | null;
    state?: string | null;
    homeAddress?: string | null;
    city?: string | null;
    phoneNumber?: string | null;
    occupation?: string | null;
    occupationInfo?: string | null;
}

