/**
 * Transfusion API
 * API used for the transfusion centers: user administration, reservation management and transfusion auditing.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginCommand { 
    userName?: string | null;
    password?: string | null;
}

